ekf_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    use_control: false
    
    # Frame IDs
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    
    # Sensor inputs
    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, true,
                   false, false, false]
    
    imu0: /imu  # If you have IMU
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false]